language: go


go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

before_script:
  - go get -t -v github.com/caser789/rpcj/...

script:
 - go test -v ./...

notifications:
  email:
    recipients: jiao.xuejiao@gmail.com
    on_success: change
    on_failure: always
